emer/axon

- examples/bench/bench.go
- examples/bench/plot.gnuplot
- examples/bench/profiling_notes.txt
Flag to enable cpu profiling.
Also added a script that uses gnuplot to make a graph from the training data.
Also added notes on how to use the profiling tool.
> Add a cpu profile flag

- .github/workflows/build.yml
- README.md
I don't know if this works without creating accounts and granting permissions on the codecov website but let's give it a try.
I wish we could host this ourselves though but not now.
> try codecov for code coverage

- examples/bench/bench.go
I save the file every epoch because it's nice to see a plot while training.
I also added the number of units to the file so I can plot the different runs in different files.
Misc: I removed the space in the key because that breaks some CSV programs.
> Save the log file every epoch

- README.md
- axon/Makefile
- axon/basic_test.go
- axon/layer.go
- axon/version.go
- examples/deep_fsa/deep_fsa.go
- examples/deep_fsa/params.go
- examples/ra25/README.md
- examples/ra25/params.go
- examples/ra25/ra25.go
- examples/ra25x/params.go
- examples/ra25x/ra25x.go
- fsfffb/README.md
- fsfffb/fsfffb.go
- fsfffb/inhib.go
Skip ing a couple of tests until this final inhibition stuff is finalized.
> Added Clamp flag to fs-fffb -- cleaner logic there and FBs were adding to clamped layers.  Also FS0Ext expt.

- .gitignore
- axon/layer_test.go
- axon/network.go
- axon/networkbase_test.go
- axon/neuron.go
- axon/neuron_test.go
The tests are nothing fancy for now.
I also refactored the `SizeReport` function for readability while I was doing some calculation around memory bandwidth. If you don't like the renamings, I can undo that one commit, it's not important to me.
> Add more tests for Layer + Neuron

- axon/Makefile
- axon/act.go
- axon/basic_test.go
- axon/layer.go
- axon/learn.go
- axon/neuron.go
- axon/version.go
- examples/ra25x/params.go
- examples/ra25x/ra25x.go
- pcore/pt.go
also added GeTrgAvg and compute that dynamically based on updated values
> SSGi -> VmDend -- in ra25x tests it can prevent positive feedback loop on nmda

- .github/workflows/build.yml
- examples/bench/bench.go
- examples/bench/bench_test.go
- examples/bench/run_bench.sh
Also switch from custom main to use testing.B.
Can get a cpu profile with the go test command.
Co-authored-by: Simon Boehm <simonboehm@mailbox.org>
> add network convergence check to bench

- axon/network.go
- axon/prjn.go
- axon/threads.go
- Rename LearnFn as PrjnFun
- Rename some hard-to-read indices in SendSpike
> Small renamings

- examples/bench/run_hardware.sh
Should've been included in PR #95
> Update the run_hardware script after refactor

- pvlv/network.go
> add negative us

- .github/workflows/build.yml
Quick test to see how much faster this'd make our CI runners.
> Test: Parallelize GH actions

- examples/bench/run_bench_pgo.sh
Gopher's Slack told me how to actually get the compiler to log all optimization decisions, not just the current module's.
> Small amendment to PGO script

- .github/workflows/build.yml
hopefully will speed things up overall
> move -race from coverage to test

- axon/deep_net.go
- axon/helpers.go
- axon/layerparams.go
- axon/logging.go
- axon/network.go
- axon/networkbase.go
- axon/pcore_net.go
- examples/boa/boa.go
- examples/boa/params.go
- examples/inhib/inhib.go
- examples/ra25/ra25.go
Added new LayersByType network function that uses enums so there is no chance of silent errors! 
Also fixes in PTMaintLayer using modulation.  Boa working better but still some issues.
Will have some more fixes later tonight before ready to merge.
> Many bugs fixed, mostly with non-updates to new LayerTypes names

- axon/layer_compute.go
- axon/layerparams.go
- examples/boa/boa.go
- examples/boa/boa_test.go
I also added a test that runs tiny boa for one epoch and reports any race conditions. That test would've caught this issue pre-merge.
> Fix racecondition in PostSpike

- examples/bench/run_bench.sh
Should've done this much earlier, I was always uncommenting some of the model size and git stashing on every branch switch, annoying.
> QoL: run_bench.sh make model size configurable

- axon/Makefile
- axon/version.go
just updating version for initial benchmarking before sender based.
> v1.7.23 release -- version.go updated

- axon/Makefile
- axon/context.go
- axon/version.go
- examples/boa/boa.go
- examples/pvlv/pvlv.go
Erdal already did this in his approach env.. need it in eboa..
> add context.PVLVInitUS separate from PVLVSetUS 

- axon/deep_net.go
Change-Id: I315b75e70fb958a8f104ba6f7a14b9c1a82d98b4
> improve doc for ConnectToPulv

- examples/boa/approach_env.go
- examples/boa/boa.go
makes the code much more readable IMHO
Change-Id: Ibb1c6d5d5d79f8c6002931dde602df9786777ad6
> named constant for no US

- examples/boa/approach_env.go
Change-Id: I0db12e51503937a248db64b497d06ef75408fe29
> instinct env: simplify setting ev.US

- axon/gpu.go
- axon/gpu_test.go
> gpu syndatan fix

- axon/Makefile
- axon/version.go
Change-Id: I8962756eb12f6f73dce74486b4d0b7b3ad8bf576
> v1.8.6 release -- version.go updated

- examples/boa/boa.go
This branch is named incorrectly but it is just a one-off to update this connectivity.  should be merged after the previous PR on which it is based.
> Update axon boa example to obelisk ALM, M1, VL connectivity

- axon/Makefile
- axon/version.go
- go.mod
- go.sum
update to emergent 23 with bugfix
> v1.8.11 release -- version.go updated

- axon/looper.go
- examples/bench_objrec/config.go
- examples/bench_objrec/objrec.go
- examples/boa/boa.go
- examples/deep_fsa/deep_fsa.go
- examples/deep_move/deep_move.go
- examples/deep_music/deep_music.go
- examples/hip/hip.go
- examples/inhib/inhib.go
- examples/mpi/ra25.go
- examples/pcore/pcore.go
- examples/pvlv/pvlv.go
- examples/ra25/ra25.go
- examples/ra25x/ra25x.go
- examples/rl/rl.go
…to guarantee that counters are updated at right time -- simplifies looper logic and ensures updt -- eboa was not syncd..
also fixed a few README urls
> LooperUpdtNetView now takes the NetViewCounters function as an arg
